/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConstellationRouteImport } from './routes/constellation'
import { Route as MethodRouteImport } from './routes/method'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstellationRoute = ConstellationRouteImport.update({
  id: '/constellation',
  path: '/constellation',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/constellation': typeof ConstellationRoute
  '/method': typeof MethodRoute
  '/api/catalog': typeof ApiCatalogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/constellation': typeof ConstellationRoute
  '/method': typeof MethodRoute
  '/api/catalog': typeof ApiCatalogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/constellation': typeof ConstellationRoute
  '/method': typeof MethodRoute
  '/api/catalog': typeof ApiCatalogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/constellation' | '/method' | '/api/catalog'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/constellation' | '/method' | '/api/catalog'
  id: '__root__' | '/' | '/constellation' | '/method' | '/api/catalog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConstellationRoute: typeof ConstellationRoute
  MethodRoute: typeof MethodRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constellation': {
      id: '/constellation'
      path: '/constellation'
      fullPath: '/constellation'
      preLoaderRoute: typeof ConstellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConstellationRoute: ConstellationRoute,
  MethodRoute: MethodRoute,
  ApiCatalogRoute: ApiCatalogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
